### ISSUE TITLE
marktzeit MVP

### ISSUE THREAD

**Issue by firstdayofjune** [firstdayofjune/marktzeit#1]
**User Stories**
As a super market customer I want to avoid packed super markets, in order to prevent an infection with the corona virus.

As a retailer I want my employees to stay healthy, in order to keep my super market running.

**Solution**
To serve a customers needs, the first prototype should should allow a customer (further _user_) to:

- [ ] Search through a list of supermarkets (#3, #4)
- [ ] View the time slots available for a market (#5)
- [x] Create/register an account (given email-address and password) 
- [x] Login to the website using that account 

A logged in user should be able to:
- [ ] Book one of the available slots (#5)
- [ ] Cancel a (future) booking (#6)
- [ ] Show a list of the slots he booked (#6)
